# Generated by Django 3.2.3 on 2021-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=105)),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(default='uncatpegorized', max_length=255),
        ),
    ]
