# Generated by Django 3.2.3 on 2021-05-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20210527_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/main/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/optional/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/optional/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/optional/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/optional/%Y/%m/%d/'),
        ),
    ]
