# Generated by Django 3.2.3 on 2021-05-29 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0004_auto_20210528_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding_auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Biggin_Price', models.IntegerField(default=0.0)),
                ('bidding_date', models.DateField(auto_now_add=True)),
                ('bdding_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bdding_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.auctionitem')),
            ],
        ),
    ]
