# Generated by Django 3.2.3 on 2021-06-03 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_bidding_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding_auction',
            name='bdding_author',
        ),
        migrations.AddField(
            model_name='bidding_auction',
            name='bdding_author_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidding_auction',
            name='bdding_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biddings', to='shop_app.auctionitem'),
        ),
    ]
